version: '3.8'

services:
# Lo relacionado a la aplicacion express
  app:
    build: .
    ports:
      - "3001:3001"
    env_file:
      - .env
    depends_on:
      - mongo
    restart: unless-stopped

    #base de datos de mongo
  mongo:
    image: mongo:8.0
    ports: 
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

volumes:
  mongo_data: